extension RawLine {

	public func make<Result, A:RawColumnConvertible where A == A.ConvertedType>(creation:(A)->Result)(from a:Int) throws -> Result {

		return try Converter((self.column(a) as A)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType>(creation:(A, B)->Result)(from a:Int, _ b:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType>(creation:(A, B, C)->Result)(from a:Int, _ b:Int, _ c:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType>(creation:(A, B, C, D)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int) throws -> Result {
		
		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType>(creation:(A, B, C, D, E)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType>(creation:(A, B, C, D, E, F)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType>(creation:(A, B, C, D, E, F, G)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType>(creation:(A, B, C, D, E, F, G, H)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible, L:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType, L == L.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K, L)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int, _ l:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K, self.column(l) as L)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible, L:RawColumnConvertible, M:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType, L == L.ConvertedType, M == M.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K, L, M)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int, _ l:Int, _ m:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K, self.column(l) as L, self.column(m) as M)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible, L:RawColumnConvertible, M:RawColumnConvertible, N:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType, L == L.ConvertedType, M == M.ConvertedType, N == N.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K, L, M, N)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int, _ l:Int, _ m:Int, _ n:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K, self.column(l) as L, self.column(m) as M, self.column(n) as N)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible, L:RawColumnConvertible, M:RawColumnConvertible, N:RawColumnConvertible, O:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType, L == L.ConvertedType, M == M.ConvertedType, N == N.ConvertedType, O == O.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int, _ l:Int, _ m:Int, _ n:Int, _ o:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K, self.column(l) as L, self.column(m) as M, self.column(n) as N, self.column(o) as O)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible, L:RawColumnConvertible, M:RawColumnConvertible, N:RawColumnConvertible, O:RawColumnConvertible, P:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType, L == L.ConvertedType, M == M.ConvertedType, N == N.ConvertedType, O == O.ConvertedType, P == P.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int, _ l:Int, _ m:Int, _ n:Int, _ o:Int, _ p:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K, self.column(l) as L, self.column(m) as M, self.column(n) as N, self.column(o) as O, self.column(p) as P)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible, L:RawColumnConvertible, M:RawColumnConvertible, N:RawColumnConvertible, O:RawColumnConvertible, P:RawColumnConvertible, Q:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType, L == L.ConvertedType, M == M.ConvertedType, N == N.ConvertedType, O == O.ConvertedType, P == P.ConvertedType, Q == Q.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int, _ l:Int, _ m:Int, _ n:Int, _ o:Int, _ p:Int, _ q:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K, self.column(l) as L, self.column(m) as M, self.column(n) as N, self.column(o) as O, self.column(p) as P, self.column(q) as Q)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible, L:RawColumnConvertible, M:RawColumnConvertible, N:RawColumnConvertible, O:RawColumnConvertible, P:RawColumnConvertible, Q:RawColumnConvertible, R:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType, L == L.ConvertedType, M == M.ConvertedType, N == N.ConvertedType, O == O.ConvertedType, P == P.ConvertedType, Q == Q.ConvertedType, R == R.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int, _ l:Int, _ m:Int, _ n:Int, _ o:Int, _ p:Int, _ q:Int, _ r:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K, self.column(l) as L, self.column(m) as M, self.column(n) as N, self.column(o) as O, self.column(p) as P, self.column(q) as Q, self.column(r) as R)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible, L:RawColumnConvertible, M:RawColumnConvertible, N:RawColumnConvertible, O:RawColumnConvertible, P:RawColumnConvertible, Q:RawColumnConvertible, R:RawColumnConvertible, S:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType, L == L.ConvertedType, M == M.ConvertedType, N == N.ConvertedType, O == O.ConvertedType, P == P.ConvertedType, Q == Q.ConvertedType, R == R.ConvertedType, S == S.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int, _ l:Int, _ m:Int, _ n:Int, _ o:Int, _ p:Int, _ q:Int, _ r:Int, _ s:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K, self.column(l) as L, self.column(m) as M, self.column(n) as N, self.column(o) as O, self.column(p) as P, self.column(q) as Q, self.column(r) as R, self.column(s) as S)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible, L:RawColumnConvertible, M:RawColumnConvertible, N:RawColumnConvertible, O:RawColumnConvertible, P:RawColumnConvertible, Q:RawColumnConvertible, R:RawColumnConvertible, S:RawColumnConvertible, T:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType, L == L.ConvertedType, M == M.ConvertedType, N == N.ConvertedType, O == O.ConvertedType, P == P.ConvertedType, Q == Q.ConvertedType, R == R.ConvertedType, S == S.ConvertedType, T == T.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int, _ l:Int, _ m:Int, _ n:Int, _ o:Int, _ p:Int, _ q:Int, _ r:Int, _ s:Int, _ t:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K, self.column(l) as L, self.column(m) as M, self.column(n) as N, self.column(o) as O, self.column(p) as P, self.column(q) as Q, self.column(r) as R, self.column(s) as S, self.column(t) as T)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible, L:RawColumnConvertible, M:RawColumnConvertible, N:RawColumnConvertible, O:RawColumnConvertible, P:RawColumnConvertible, Q:RawColumnConvertible, R:RawColumnConvertible, S:RawColumnConvertible, T:RawColumnConvertible, U:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType, L == L.ConvertedType, M == M.ConvertedType, N == N.ConvertedType, O == O.ConvertedType, P == P.ConvertedType, Q == Q.ConvertedType, R == R.ConvertedType, S == S.ConvertedType, T == T.ConvertedType, U == U.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int, _ l:Int, _ m:Int, _ n:Int, _ o:Int, _ p:Int, _ q:Int, _ r:Int, _ s:Int, _ t:Int, _ u:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K, self.column(l) as L, self.column(m) as M, self.column(n) as N, self.column(o) as O, self.column(p) as P, self.column(q) as Q, self.column(r) as R, self.column(s) as S, self.column(t) as T, self.column(u) as U)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible, L:RawColumnConvertible, M:RawColumnConvertible, N:RawColumnConvertible, O:RawColumnConvertible, P:RawColumnConvertible, Q:RawColumnConvertible, R:RawColumnConvertible, S:RawColumnConvertible, T:RawColumnConvertible, U:RawColumnConvertible, V:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType, L == L.ConvertedType, M == M.ConvertedType, N == N.ConvertedType, O == O.ConvertedType, P == P.ConvertedType, Q == Q.ConvertedType, R == R.ConvertedType, S == S.ConvertedType, T == T.ConvertedType, U == U.ConvertedType, V == V.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int, _ l:Int, _ m:Int, _ n:Int, _ o:Int, _ p:Int, _ q:Int, _ r:Int, _ s:Int, _ t:Int, _ u:Int, _ v:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K, self.column(l) as L, self.column(m) as M, self.column(n) as N, self.column(o) as O, self.column(p) as P, self.column(q) as Q, self.column(r) as R, self.column(s) as S, self.column(t) as T, self.column(u) as U, self.column(v) as V)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible, L:RawColumnConvertible, M:RawColumnConvertible, N:RawColumnConvertible, O:RawColumnConvertible, P:RawColumnConvertible, Q:RawColumnConvertible, R:RawColumnConvertible, S:RawColumnConvertible, T:RawColumnConvertible, U:RawColumnConvertible, V:RawColumnConvertible, W:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType, L == L.ConvertedType, M == M.ConvertedType, N == N.ConvertedType, O == O.ConvertedType, P == P.ConvertedType, Q == Q.ConvertedType, R == R.ConvertedType, S == S.ConvertedType, T == T.ConvertedType, U == U.ConvertedType, V == V.ConvertedType, W == W.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int, _ l:Int, _ m:Int, _ n:Int, _ o:Int, _ p:Int, _ q:Int, _ r:Int, _ s:Int, _ t:Int, _ u:Int, _ v:Int, _ w:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K, self.column(l) as L, self.column(m) as M, self.column(n) as N, self.column(o) as O, self.column(p) as P, self.column(q) as Q, self.column(r) as R, self.column(s) as S, self.column(t) as T, self.column(u) as U, self.column(v) as V, self.column(w) as W)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible, L:RawColumnConvertible, M:RawColumnConvertible, N:RawColumnConvertible, O:RawColumnConvertible, P:RawColumnConvertible, Q:RawColumnConvertible, R:RawColumnConvertible, S:RawColumnConvertible, T:RawColumnConvertible, U:RawColumnConvertible, V:RawColumnConvertible, W:RawColumnConvertible, X:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType, L == L.ConvertedType, M == M.ConvertedType, N == N.ConvertedType, O == O.ConvertedType, P == P.ConvertedType, Q == Q.ConvertedType, R == R.ConvertedType, S == S.ConvertedType, T == T.ConvertedType, U == U.ConvertedType, V == V.ConvertedType, W == W.ConvertedType, X == X.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int, _ l:Int, _ m:Int, _ n:Int, _ o:Int, _ p:Int, _ q:Int, _ r:Int, _ s:Int, _ t:Int, _ u:Int, _ v:Int, _ w:Int, _ x:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K, self.column(l) as L, self.column(m) as M, self.column(n) as N, self.column(o) as O, self.column(p) as P, self.column(q) as Q, self.column(r) as R, self.column(s) as S, self.column(t) as T, self.column(u) as U, self.column(v) as V, self.column(w) as W, self.column(x) as X)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible, L:RawColumnConvertible, M:RawColumnConvertible, N:RawColumnConvertible, O:RawColumnConvertible, P:RawColumnConvertible, Q:RawColumnConvertible, R:RawColumnConvertible, S:RawColumnConvertible, T:RawColumnConvertible, U:RawColumnConvertible, V:RawColumnConvertible, W:RawColumnConvertible, X:RawColumnConvertible, Y:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType, L == L.ConvertedType, M == M.ConvertedType, N == N.ConvertedType, O == O.ConvertedType, P == P.ConvertedType, Q == Q.ConvertedType, R == R.ConvertedType, S == S.ConvertedType, T == T.ConvertedType, U == U.ConvertedType, V == V.ConvertedType, W == W.ConvertedType, X == X.ConvertedType, Y == Y.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int, _ l:Int, _ m:Int, _ n:Int, _ o:Int, _ p:Int, _ q:Int, _ r:Int, _ s:Int, _ t:Int, _ u:Int, _ v:Int, _ w:Int, _ x:Int, _ y:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K, self.column(l) as L, self.column(m) as M, self.column(n) as N, self.column(o) as O, self.column(p) as P, self.column(q) as Q, self.column(r) as R, self.column(s) as S, self.column(t) as T, self.column(u) as U, self.column(v) as V, self.column(w) as W, self.column(x) as X, self.column(y) as Y)).into(creation)
	}

	public func make<Result, A:RawColumnConvertible, B:RawColumnConvertible, C:RawColumnConvertible, D:RawColumnConvertible, E:RawColumnConvertible, F:RawColumnConvertible, G:RawColumnConvertible, H:RawColumnConvertible, I:RawColumnConvertible, J:RawColumnConvertible, K:RawColumnConvertible, L:RawColumnConvertible, M:RawColumnConvertible, N:RawColumnConvertible, O:RawColumnConvertible, P:RawColumnConvertible, Q:RawColumnConvertible, R:RawColumnConvertible, S:RawColumnConvertible, T:RawColumnConvertible, U:RawColumnConvertible, V:RawColumnConvertible, W:RawColumnConvertible, X:RawColumnConvertible, Y:RawColumnConvertible, Z:RawColumnConvertible where A == A.ConvertedType, B == B.ConvertedType, C == C.ConvertedType, D == D.ConvertedType, E == E.ConvertedType, F == F.ConvertedType, G == G.ConvertedType, H == H.ConvertedType, I == I.ConvertedType, J == J.ConvertedType, K == K.ConvertedType, L == L.ConvertedType, M == M.ConvertedType, N == N.ConvertedType, O == O.ConvertedType, P == P.ConvertedType, Q == Q.ConvertedType, R == R.ConvertedType, S == S.ConvertedType, T == T.ConvertedType, U == U.ConvertedType, V == V.ConvertedType, W == W.ConvertedType, X == X.ConvertedType, Y == Y.ConvertedType, Z == Z.ConvertedType>(creation:(A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z)->Result)(from a:Int, _ b:Int, _ c:Int, _ d:Int, _ e:Int, _ f:Int, _ g:Int, _ h:Int, _ i:Int, _ j:Int, _ k:Int, _ l:Int, _ m:Int, _ n:Int, _ o:Int, _ p:Int, _ q:Int, _ r:Int, _ s:Int, _ t:Int, _ u:Int, _ v:Int, _ w:Int, _ x:Int, _ y:Int, _ z:Int) throws -> Result {

		return try Converter((self.column(a) as A, self.column(b) as B, self.column(c) as C, self.column(d) as D, self.column(e) as E, self.column(f) as F, self.column(g) as G, self.column(h) as H, self.column(i) as I, self.column(j) as J, self.column(k) as K, self.column(l) as L, self.column(m) as M, self.column(n) as N, self.column(o) as O, self.column(p) as P, self.column(q) as Q, self.column(r) as R, self.column(s) as S, self.column(t) as T, self.column(u) as U, self.column(v) as V, self.column(w) as W, self.column(x) as X, self.column(y) as Y, self.column(z) as Z)).into(creation)
	}
}
